# Generated by Django 5.0.9 on 2026-08-22 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_organization', models.CharField(max_length=150)),
                ('quote_en', models.TextField()),
                ('quote_sw', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])])),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_sw', models.CharField(max_length=100)),
                ('description_en', models.TextField()),
                ('description_sw', models.TextField()),
                ('icon', models.CharField(default='shield-check', help_text='Jina la Bootstrap/Feather icon', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImpactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Mfano: 100+, 50+, 15+', max_length=20)),
                ('label_en', models.CharField(max_length=100)),
                ('label_sw', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('role_en', models.CharField(max_length=150)),
                ('role_sw', models.CharField(max_length=150)),
                ('bio_en', models.TextField(blank=True)),
                ('bio_sw', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('linkedin_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_leadership', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
