# Generated by Django 5.0.9 on 2026-08-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_sw', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('summary_en', models.TextField()),
                ('summary_sw', models.TextField()),
                ('icon', models.CharField(default='bar-chart-2', max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
