# Generated by Django 5.0.9 on 2026-08-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=150)),
                ('title_sw', models.CharField(max_length=150)),
                ('description_en', models.TextField()),
                ('description_sw', models.TextField()),
                ('icon', models.CharField(default='clipboard', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
