# Generated by Django 5.0.9 on 2026-08-22 06:45

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_sw', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('body_en', models.TextField()),
                ('body_sw', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('author_name', models.CharField(max_length=150)),
                ('published_date', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_sw', models.CharField(max_length=200)),
                ('summary_en', models.TextField()),
                ('summary_sw', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='publications/covers/')),
                ('document', models.FileField(help_text='PDF pekee, upeo wa 5MB.', upload_to='publications/files/', validators=[core.validators.validate_document_file])),
                ('published_date', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
