# Generated by Django 5.0.9 on 2026-08-22 06:45

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('tor_document', models.FileField(blank=True, help_text='Terms of Reference (PDF/DOC), si lazima. Upeo wa 5MB.', null=True, upload_to='proposals/tor/', validators=[core.validators.validate_document_file])),
                ('status', models.CharField(choices=[('new', 'Mpya'), ('reviewing', 'Inapitiwa'), ('contacted', 'Mteja Amewasiliana Naye'), ('closed', 'Imefungwa')], default='new', max_length=20)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectors.sector')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
